config/routes.rb
Rails.application.routes.draw do
  get 'savings/mypage'
  #resources :savings, param: :user_id
  get 'home/top' => "home#top"
  #get "savings/main" => "savings#main"
  get "savings/main/:id" => "savings#main"
  get "savings/mypage/:id" => "savings#mypage"
  post "home/top" => "home#create"
  post "savings/main/:id" => "savings#create"
  post "savings/mypage/:id" => "savings#update"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#top"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
end

app/models/saving.rb
class Saving < ApplicationRecord
    belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :logs
  has_one :savings
    
  validates :name, presence:true, uniqueness: true

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "5000億円欲しくない！？！？！？欲しい！！！！僕も！！！！"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def create
    @user = User.new(name:params[:name])
    @user.save
    @saving = Saving.new(target: 0, current: 0, system_id: @user.id)
    @saving.save
    redirect_to("/savings/main/#{@user.id}")
  end
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController

    def main
        # @savings = Saving.first
        @user_id = params[:id]
        @user = User.find(params[:id])
        @savings = Saving.find_by(system_id: params[:id])
        @savings_current = @savings.current
        @savings_target = @savings.target
    end
    
    def new
        @user = User.new
        @savings = Saving.new
    end
    

    def create
        @savings = Saving.find_by(system_id: params[:id])
        @savingsAdd = (@savings.current + params[:saving][:current].to_i)
        
        # 成功した時
        # if @savings.save
        if @savings.update(current: @savingsAdd)
            redirect_to "/savings/main/#{params[:id]}", notice: "保存しました"
        
        # 失敗
        else
            render :new, notice: "保存できませんでした"
        end
        
    end
    
    
    def update
        
        @savings = Saving.find_by(system_id: params[:id])
        @savingsNew = params[:saving][:target].to_i
        @user_id = params[:id]
        # 成功した時
        # if @savings.save
        if @savings.update(target: @savingsNew)
            redirect_to "/savings/main/#{@user_id}", notice: "保存しました"
        
        # 失敗
        else
            render :new, notice: "保存できませんでした"
        end
    end
    
    private
    
    def savings_params
        params.require(:saving).permit(:current, :system_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/savings_helper.rb
module SavingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CHALLING</title>
  </head>
  <body>
    <!-- トップページ -->
    <%= image_tag("CHALLINGLogo.png", :class => "title-logo") %>
    <div class="button-wrap">
        <div class="button" id="buttonL">
            はじめる
        </div>
        <div class="button" id="buttonR">
            Sing In
        </div>
        <p class="buttonText" id="buttonTextL">
            はじめての方
        </p>
        <p class="buttonText" id="buttonTextR">
            アカウントをお持ちの方
        </p>
    </div>
    
    <!-- Sign Up -->
    <div class="signup">
        <p class="signuptext">
        ユーザ名を<br>
        入力してください</p>
        <%= form_for("/home/top") do |f| %>
           <%= f.label :name %>
        <textarea name="name"></textarea>
           <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
<!--        <form>-->
<!--            <input type="text" name="email" placeholder="Email Address" class="textbox" />-->
<!--        </form>-->
<!--        <form>-->
<!--            <input type="password" name="pass" placeholder="Password" class="textbox" />-->
<!--        </form>-->
<!--        <form>-->
<!--            <input type="password" name="passRe" placeholder="Password(確認用)" class="textbox" />-->
<!--        </form>-->
<!--        <div class="button">-->
<!--            <a href="./savings/main">Sign Up</a>-->
<!--        </div>-->
    </div>
      
    <!-- Sign In -->
    <div class="signin">
        <p class="signintext">ログインします<br>
        メールアドレスとパスワードを<br>
        入力してください</p>
        <form>
            <input type="text" name="email" placeholder="Email Address" class="textbox" />
        </form>
        <form>
            <input type="password" name="pass" placeholder="Password" class="textbox" />
        </form>
        <div class="button">
            <a href="./savings/main">Sign In</a>
        </div>
    </div>
    
    <!-- グレーアウト -->
    <div id="overlay"></div>
    
    <!-- フッター -->
    <footer>
        <%= image_tag("neko.png") %>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/savings/_form.html.erb
<%= form_with(model: saving, local: true) do |form| %>
  <% if saving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(saving.errors.count, "error") %> prohibited this saving from being saved:</h2>

      <ul>
      <% saving.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :target %>
    <%= form.text_field :target %>
  </div>

  <div class="field">
    <%= form.label :current %>
    <%= form.text_field :current %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/savings/edit.html.erb
<h1>Editing Saving</h1>

<%= render 'form', saving: @saving %>

<%= link_to 'Show', @saving %> |
<%= link_to 'Back', savings_path %>

app/views/savings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Savings</h1>

<table>
  <thead>
    <tr>
      <th>Target</th>
      <th>Current</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @savings.each do |saving| %>
      <tr>
        <td><%= saving.target %></td>
        <td><%= saving.current %></td>
        <td><%= link_to 'Show', saving %></td>
        <td><%= link_to 'Edit', edit_saving_path(saving) %></td>
        <td><%= link_to 'Destroy', saving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Saving', new_saving_path %>

app/views/savings/main.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CHALLING</title>
  </head>
  <body>
    <!-- ヘッダー -->
    <header>
      <div class="header-logo">
        <a href="/"><%= image_tag("CHALLINGLogos.png", :class => "header-logo") %></a>
      </div>
      <div class="mypage">
          <%= image_tag("staff.png", :class => "mypage-icon") %>
          <%= link_to "マイページ", "/savings/mypage/#{@user_id}" %>
      </div>
    </header>
    <%= @user.name %>
    <!-- 貯金額の表示・入力 -->
    <div class="savings-wrap">
        <p class="title" id="now-title">現在の貯金</p>
        <p class="value" id="now-value"><%= @savings_current %> yen</p>
        <p class="title" id="goal-title">目標金額</p>
        <p class="value" id="goal-value"><%= @savings_target %> yen</p>

        <%= form_for("saving") do |f| %>
            <%= f.text_field :current, :class => "textbox", :placeholder => "数字を入力" %>
        
            <%= f.hidden_field :system_id, :value => @user_id %>

            <%= image_submit_tag "Add.png", :id => "plus" %>
        <% end %>
    </div>

    <!-- フッター -->
    <footer>
        <%= image_tag("neko.png") %>
    </footer>
  </body>
</html>

app/views/savings/mypage.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>CHALLING</title>
  </head>
  <body>
    <!-- ヘッダー -->
    <header>
      <div class="header-logo">
        <a href="/"><%= image_tag("CHALLINGLogos.png", :class => "header-logo") %></a>
      </div>
      <div class="mypage">
          <%= image_tag("staff.png", :class => "mypage-icon") %>
          <%= link_to "マイページ", "/savings/mypage/#{@user_id}" %>
      </div>
    </header>
    <!-- 目標額入力 -->
    <div class="savings-wrap">

        <%= form_for("saving") do |f| %>
            <%= f.text_field :target, :class => "textbox", :placeholder => "目標金額を入力" %>
        
            <%= f.hidden_field :system_id, :value => @user_id %>

            <%= image_submit_tag "Add.png", :id => "plus" %>
        <% end %>
    </div>
      
    <div class="button" id="back">
        <%= link_to "戻る", :back %>
    </div>

    <!-- フッター -->
    <footer>
        <%= image_tag("neko.png") %>
    </footer>
  </body>
</html>

app/views/savings/new.html.erb
<h1>New Saving</h1>

<%= render 'form', saving: @saving %>

<%= link_to 'Back', savings_path %>

app/views/savings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Target:</strong>
  <%= @saving.target %>
</p>

<p>
  <strong>Current:</strong>
  <%= @saving.current %>
</p>

<%= link_to 'Edit', edit_saving_path(@saving) %> |
<%= link_to 'Back', savings_path %>